hrapp/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'hrapp'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('home/', views.home, name='home'),
    path('login/', auth_views.LoginView.as_view(template_name='hrapp/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='hrapp/logout.html'), name='logout'),
    path('manage/', views.TimeTableView.as_view(), name='manage'),
    path('schedule_list/', views.TimeTableList.as_view(), name='schedule_list'),


]

studentapp/urls.py
from django.urls import path
from .views import student_register, course_view, each_course
from django.contrib.auth import views as auth_views

app_name = 'studentapp'

urlpatterns = [
    path('', student_register, name='student_register'),
    path('view/', course_view, name='course_view'),
    path('<int:course_id>', each_course, name='each_course'),
    path('login/', auth_views.LoginView.as_view(template_name='studentapp/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='studentapp/logout.html'), name='logout'),
]

user_reg_proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('userapp.urls')),
                  path('course/', include('courseapp.urls')),
                  path('trainer/', include('trainers.urls')),
                  path('batch/', include('batchapp.urls')),
                  path('student/', include('studentapp.urls')),
                  path('hr/', include('hrapp.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

studentapp/models.py
from django.db import models
from courseapp.models import CourseModel
from batchapp.models import Batch
from datetime import datetime
from django.contrib.auth.models import AbstractUser


# Create your models here.

class Student(models.Model):
    name = models.CharField(max_length=50)
    address = models.CharField(max_length=50)
    phone = models.IntegerField(unique=True)
    email = models.EmailField(max_length=50, unique=True)
    select_course = models.ForeignKey(CourseModel, on_delete=models.CASCADE)
    select_batch = models.ForeignKey(Batch, on_delete=models.CASCADE)
    date = models.DateField(default=datetime.now)

    def __str__(self):
        return self.name

studentapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.forms import ModelForm
from django import forms
from .models import Student
from django.contrib import messages
from courseapp.models import CourseModel
from django.core.paginator import Paginator
from django.core.validators import validate_email


class StudentForm(ModelForm):
    class Meta:
        model = Student
        fields = '__all__'


# validations

def clean_phone(self, *args, **kwargs):
    phone = self.cleaned_data.get('phone')
    if len(phone) > 8:
        raise forms.ValidationError('not a valid number')
    # Create your views here.


def student_register(request, template_name='studentapp/apply.html'):
    form = StudentForm(request.POST or None)
    if form.is_valid():
        form.save()
        name = form.cleaned_data.get('name')
        course = form.cleaned_data.get('select_course')
        messages.success(request, f'{name} successfully applied for the course {course}')
        return redirect('studentapp:student_register')
    else:
        form = StudentForm()
    return render(request, template_name, {'form': form})


def course_view(request, template_name='studentapp/courses.html'):
    courses = CourseModel.objects.order_by('name')
    # search feature
    query = request.GET.get("q")
    if query:
        courses = courses.filter(name__icontains=query)

    paginator = Paginator(courses, 3)
    page = request.GET.get('page')
    page_courses = paginator.get_page(page)

    context = {
        'courses': page_courses
    }

    return render(request, template_name, context)


# view for each courses
def each_course(request, course_id, template_name='studentapp/each_course.html'):
    course = get_object_or_404(CourseModel, pk=course_id)
    return render(request, template_name, {'course': course})

templates/studentapp/apply.html
{% extends 'studentapp/base.html' %}


{% load crispy_forms_tags%}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h1 class="display-6"></h1>
            <form method="POST">
                {% csrf_token %}
                <fieldset class="form-group">
                    {{form|crispy}}

                </fieldset>
                <div class="form-group">
                    <button class="btn btn-outline-info btn-block" type="submit">
                        Apply
                    </button>
                </div>
            </form>
        </div>

    </div>
</div>

{% endblock %}

templates/studentapp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB"
    crossorigin="anonymous">


    <link rel="stylesheet" href="{% static 'course_style.css' %}">
    <link rel="stylesheet" href="{% static 'footer.css' %}">

    <title>Document</title>
</head>
<body>

    <!--navbar-->

     {% include 'partial/_navbar2.html' %}


    {% if messages %}
<div class="container">
    <div class="row">

        <div class="col-md-6">
            {% for msg in messages %}

            <div class="alert alert-{{msg.tags}}">

                {{msg}}
            </div>
            {% endfor %}

        </div>
        {% endif %}

    </div>
</div>
    <div class="box-1" style="min-height: 100vh">
    {% block content%}



    {% endblock %}
    </div>




    <script src="{% static 'js/button_click.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"
        crossorigin="anonymous"></script>

</body>
</html>

templates/studentapp/courses.html
{% extends 'studentapp/base.html' %}
{% load static %}
{% load humanize %}
{% block content %}



<section id="showcase-inner" class="py-5 text-white">
    <div class="container">
        <div class="row text-center">
            <div class="col-md-12">
                <h1 class="display-4">Browse Courses</h1>
            </div>
        </div>
    </div>
</section>


<!--breadcrumb navigation-->
<section id="bc" class="mt-3">

    <div class="container">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'index_page' %}">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">Courses</li>
        </ol>
    </nav>
    </div>



 <section id="listings" class="py-4 mt-2">
    <div class="container">
      <div class="row">
        {% if courses %}
        {% for course in courses %}
        <div class="col-md-6 col-lg-4 mb-4">
          <div class="card-body" style="background: ghostwhite">
              <div class="listing-heading text-center">
                  <h4 class="text-primary"> {{course.name}}</h4>
              </div>
              <hr>
              <div class="row py-2 text-secondary">
                  <div class="col-8">
                      <p>
                        Duration: {{course.duration}}
                      </p>
                      <p>
                        Fees: {{course.fees|intcomma}}
                      </p>
                      <p>
                        Trainer: {{course.trainer}}
                      </p>
                  </div>
                  <hr>

                   <a href="{% url 'studentapp:each_course' course.id %}" class="btn btn-primary btn-block" id="button1"
                   >More Info</a>
              </div>
            </div>
        </div>
          {% endfor %}

          {% else %}
          <div class="col-md-12">No Courses</div>
          {% endif %}

      </div>

        <!--pagniation -->
         <div class="row">
        <div class="col-md-12">

          {% if courses.has_other_pages%}
          <ul class="pagination">
            {% if courses.has_previous %}
              <li class="page-item">
                <a class="page-link" href="?page={{courses.previous_page_number}}&q={{request.GET.q}}">&laquo;</a>
              </li>
            {% else %}
              <li class="page-item disabled">
                <a class="page-link">&laquo;</a>
              </li>
            {% endif %}
            {% for i in courses.paginator.page_range %}


              {% if courses.number == i %}
                <li class="page-item active">
                  <a class="page-link">{{i}}</a>
                </li>
              {% else %}

                <li class="page-item">
                  <a class="page-link" href="?page={{i}}&q={{request.GET.q}}">{{i}}</a>
                </li>
              {% endif %}
            {% endfor %}


            {% if courses.has_next %}
              <li class="page-item">
                <a href="?page={{courses.next_page_number}}&q={{request.GET.q}}" class="page-link">&raquo;</a>
              </li>
            {% else %}
              <li class="page-item disabled">
                <a class="page-link">&raquo;</a>
              </li>
            {% endif %}

          </ul>
          {% endif %}
        </div>
         </div>


    </div>
 </section>



{% endblock %}

templates/studentapp/each_course.html
{% extends 'studentapp/base.html' %}
{% load static %}
{% block content %}

<section id="showcase-inner" class="py-5 text-white">
    <div class="container">
        <div class="row text-center">
            <div class="col-md-12">
                <h1 class="display-4">{{course.name}}</h1>
            </div>
        </div>
    </div>
</section>

<!--breadcrumb -->
<section id="bc" class="mt-3">
    <div class="container">

      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{% url 'index_page' %}">Home</a></li>
          <li class="breadcrumb-item"><a href="{% url 'studentapp:course_view' %}">Courses</a></li>
          <li class="breadcrumb-item active" aria-current="page">{{course.name}}</li>
        </ol>
      </nav>
    </div>
</section>

<!--button-->
<section id="courses" class="py-4">

    <div class="container">
        <a href="{% url 'studentapp:course_view' %}" class="btn btn-secondary mb-4">
            Back to Courses
        </a>

<!--        course syllabus-->

        <div class="row mb-5">
            <div class="col-md-8">
                <h1 class="display-6">What you will be learning</h1>
                <p class="text-justify">
                  Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia recusandae esse reiciendis officia omnis non rerum dicta
              cupiditate nostrum molestias deserunt aut minus inventore animi atque, consequuntur ad fugit. Possimus culpa
              blanditiis repellendus ipsa similique ullam, natus error dolor harum. Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia recusandae esse reiciendis officia omnis non rerum dicta
              cupiditate nostrum molestias deserunt aut minus inventore animi atque, consequuntur ad fugit. Possimus culpa
              blanditiis repellendus ipsa similique ullam, natus error dolor harum.
                </p>
                <div class="mb-3">
                    <a href="{%url 'studentapp:student_register' %}" class="btn btn-outline-info">Apply Here</a>
                </div>
            </div>

        <div class="col-md-3">
            <div class="card mb-3">

                 <img class="card-img-top" src="{{course.trainer.photo.url}}" alt="trainer image">
                <div class="card-body">
                    <h5 class="card-title">Trainer</h5>
                    <h6 class="text-secondary">{{course.trainer}}</h6>
                    <hr>
                    <h6 class="text-secondary">{{course.trainer.experience}}</h6>
                </div>
            </div>
        </div>
   </div>

    </div>


</section>

{% endblock %}