hrapp/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'hrapp'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('home/', views.home, name='home'),
    path('login/', auth_views.LoginView.as_view(template_name='hrapp/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='hrapp/logout.html'), name='logout'),
    path('manage/', views.TimeTableView.as_view(), name='manage'),
    path('schedule_list/', views.TimeTableList.as_view(), name='schedule_list'),


]

user_reg_proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('userapp.urls')),
                  path('course/', include('courseapp.urls')),
                  path('trainer/', include('trainers.urls')),
                  path('batch/', include('batchapp.urls')),
                  path('student/', include('studentapp.urls')),
                  path('hr/', include('hrapp.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hrapp/models.py
from django.db import models
from batchapp.models import Batch


class ClassRoom(models.Model):
    classroom = models.CharField(max_length=5)

    def __str__(self):
        return self.classroom


class TimeTable(models.Model):
    select_batch = models.ForeignKey(Batch, on_delete=models.CASCADE)
    start_time = models.TimeField()
    end_time = models.TimeField()
    classroom = models.ForeignKey(ClassRoom, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.select_batch}'s Schedule"

hrapp/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from .hrforms import RegisterForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.views.generic import CreateView, ListView
from .models import TimeTable
from django.contrib.auth.decorators import login_required
from .hrforms import TimeTableForm
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin


# Create your views here.


def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Account created for {username}!')
            return redirect('hrapp:login')
    else:
        form = RegisterForm()
    return render(request, 'hrapp/register.html', {'form': form})


@login_required
def home(request, template_name='hrapp/home.html'):
    return render(request, template_name)


class TimeTableView(LoginRequiredMixin, CreateView):
    model = TimeTable
    form_class = TimeTableForm
    success_url = reverse_lazy('hrapp:schedule_list')


class TimeTableList(LoginRequiredMixin, ListView):
    model = TimeTable
    context_object_name = 'schedules'

hrapp/templates/hrapp/home.html
{% extends 'hrapp/base.html' %}

{% block content %}

<div class="container">
    <div class="row py-5">
    <h1 class="text-info text-center">HR Home</h1>
    </div>
    <a href="{% url 'hrapp:manage' %}">Add Timetable</a>&nbsp;&nbsp;
    <a href="{% url 'hrapp:schedule_list' %}">Manage timetable</a>
</div>

{% endblock %}

hrapp/templates/hrapp/login.html
{% extends 'hrapp/base.html' %}

{% load crispy_forms_tags %}
{% block content %}
<section id="login">
    <div class="container">
        <div class="row py-4">
            <div class="col-md-4 mx-auto">
                <div class="card">
                <div class="card-body">
                <form method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <h2 class="text-secondary border-bottom">Login</h2>
                        {{form|crispy}}
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-info btn-block">Login</button>
                    </div>
                </form>
                <div class="pt-2">
                    <small class="text-muted">Not have an Account?
                        <a href="{% url 'hrapp:register' %}" class="ml-2">
                            Sign Up
                        </a>
                    </small>
                </div>
                </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

hrapp/templates/hrapp/logout.html
{% extends 'hrapp/base.html' %}

{% block content %}
<div class="container">
    <div class="py-4">
        <p class="lead border-bottom">You Have been Logged out</p>
        <a href="{% url 'hrapp:login' %}">Login Again</a>
    </div>
</div>

{% endblock %}

hrapp/templates/hrapp/profile.html
{% extends 'hrapp/base.html' %}

{% block content %}
<section id="hrhome">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <h1>HR Home</h1>
            </div>
        </div>
    </div>
</section>

{% endblock%}

hrapp/templates/hrapp/register.html
{% extends 'hrapp/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <section id="register">
        <div class="container">
            <div class="row py-4">
                <div class="col-md-6 mx-auto">
                    <div class="card">
                    <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        <div class="form-group">
                            <h2 class="text-secondary border-bottom">
                                Register
                            </h2>
                            {{form|crispy}}
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-info btn-block">Register</button>
                        </div>
                    </form>
                    <div class="pt-2">
                        <small class="text-muted">Already have an Account?
                            <a href="{% url 'hrapp:login' %}">Sign In</a>
                        </small>
                    </div>
                    </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

hrapp/templates/hrapp/timetable_form.html
{% extends 'hrapp/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
    <div class="row py-3">
        <div class="col-sm-4 mx-auto">
            <h2 class="text-info">Manage Timetable</h2>
            <form method="POST">
    {% csrf_token %}
    <div class="form-group">
        {{form|crispy}}
    </div>
    <button type="submit" class="btn btn-info btn-block">Save</button>
  </form>
        </div>
    </div>
</div>
{% endblock %}

hrapp/templates/hrapp/timetable_list.html
{% extends 'hrapp/base.html' %}

{% block content %}
    <div class="container">
        <div class="row py-5">
            <div class="col-md-8">
                <h2 class="text-info">Time Table for Batches</h2>
                <table class="table table-striped table-hover">
                        <thead>
                            <tr>
                                <th scope="col">#</th>

                                <th scope="col">Batch</th>
                                <th scope="col">StartTime</th>
                                <th scope="col">EndTime</th>
                                <th scope="col">ClassRoom</th>
                            </tr>
                        </thead>
                {% for each in schedules %}

                        <tbody>
                            <tr>
                                <th scope="row">{{forloop.counter}}</th>

                                <td>{{each.select_batch}}</td>
                                <td>{{each.start_time}}</td>
                                <td>{{each.end_time}}</td>
                                <td>{{each.classroom}}</td>
                            </tr>
                        </tbody>


                {% endfor %}
                      </table>
            </div>
        </div>
    </div>
{% endblock %}