hrapp/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'hrapp'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('home/', views.home, name='home'),
    path('login/', auth_views.LoginView.as_view(template_name='hrapp/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='hrapp/logout.html'), name='logout'),
    path('manage/', views.TimeTableView.as_view(), name='manage'),
    path('schedule_list/', views.TimeTableList.as_view(), name='schedule_list'),


]

studentapp/urls.py
from django.urls import path
from .views import student_register, course_view, each_course
from django.contrib.auth import views as auth_views

app_name = 'studentapp'

urlpatterns = [
    path('', student_register, name='student_register'),
    path('view/', course_view, name='course_view'),
    path('<int:course_id>', each_course, name='each_course'),
    path('login/', auth_views.LoginView.as_view(template_name='studentapp/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='studentapp/logout.html'), name='logout'),
]

user_reg_proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('userapp.urls')),
                  path('course/', include('courseapp.urls')),
                  path('trainer/', include('trainers.urls')),
                  path('batch/', include('batchapp.urls')),
                  path('student/', include('studentapp.urls')),
                  path('hr/', include('hrapp.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/partial/_footer.html
  <footer id="main-footer" class="text-center p-4 bg-dark text-light">
    <div class="container">
      <div class="row">
        <div class="col">
          <p>welcome
            <span id="year">2020</span>&nbsp;music stop
          </p>
        </div>
      </div>
    </div>
  </footer>

templates/partial/_header.html
  <header id="page-header">
      <div class="container">
          <div class="row">
              <div class="col-md-6 text-center m-auto">
                  <h1>About Us</h1>
                  <p>
                      welcome to music stop
                  </p>
              </div>
          </div>
      </div>
  </header>

templates/partial/_navbar.html
 <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <div class="container">
      <a href="{% url 'index_page' %}" class="navbar-brand">Music Stop</a>
      <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
              <li class="nav-item">
                <a href="{% url 'home' %}" class="nav-link">My Home
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'logout' %}" class="nav-link">
                    Logout
                </a></li>
            {% else %}
                       <li class="nav-item">
                <a href="{% url 'home' %}" class="nav-link d-none">My Home
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'logout' %}" class="nav-link d-none">
                    Logout
                </a></li>
                  <li class="nav-item">
                        <a href="{% url 'register' %}" class="nav-link">
                            Register
                        </a>
          </li>
              <li class="nav-item">
                    <a href="{% url 'login' %}" class="nav-link">
                        Login
                    </a>

          </li>
            {% endif %}




        </ul>
      </div>
    </div>
  </nav>

templates/partial/_navbar2.html
 <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <div class="container">
      <a href="{% url 'index_page' %}" class="navbar-brand">Music Stop</a>
      <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarCollapse">



        <ul class="navbar-nav ml-auto">
          <li
                  {% if '/' == request.path %}
                    class="nav-item active"
                  {% else %}
                    class="nav-item"
                  {% endif %}
                  >
            <a href="{% url 'index_page' %}" class="nav-link">Home</a>
          </li>
          <li
            {% if 'view' in request.path %}
              class="nav-item active"
            {% else %}
              class="nav-item"
            {% endif %}
          >
            <a href="{% url 'studentapp:course_view' %}" class="nav-link">Courses</a>
          </li>
          <li
                  {% if 'about' in request.path %}
                    class="nav-item active"
                  {% else %}
                    class=nav-item
                  {% endif %}
            >
            <a href="{% url 'about_page' %}" class="nav-link">About Us</a>
          </li>
          <li
                  {% if 'contact' in request.path%}
                    class="nav-item active"
                  {% else %}
                    class="nav-item"
                  {% endif %}
          >
            <a href="{% url 'contact' %}" class="nav-link">Contact</a>
          </li>

<!--            <li> <a href="{% url 'studentapp:login' %}" class="nav-link">Login</a></li>-->
        </ul>
      </div>

  </nav>

templates/partial/_navbarhr.html
 <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <div class="container">
      <a href="{% url 'index_page' %}" class="navbar-brand">Music Stop</a>
      <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
              <li class="nav-item">
                <a href="{% url 'home' %}" class="nav-link">My Home
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'hrapp:logout' %}" class="nav-link">
                    Logout
                </a></li>
            {% else %}
                       <li class="nav-item">
                <a href="{% url 'home' %}" class="nav-link d-none">My Home
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'hrapp:logout' %}" class="nav-link d-none">
                    Logout
                </a></li>
                  <li class="nav-item">
                        <a href="{% url 'hrapp:register' %}" class="nav-link">
                            Register
                        </a>
          </li>
              <li class="nav-item">
                    <a href="{% url 'hrapp:login' %}" class="nav-link">
                        Login
                    </a>

          </li>
            {% endif %}




        </ul>
      </div>
    </div>
  </nav>